
package contreras;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.1
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "parcial_1_contreras_web_operaciones_9a", targetNamespace = "http://contreras/", wsdlLocation = "http://localhost:8080/parcial1_contreras_web_operaciones_9a/parcial_1_contreras_web_operaciones_9a?wsdl")
public class Parcial1ContrerasWebOperaciones9A_Service
    extends Service
{

    private static final URL PARCIAL1CONTRERASWEBOPERACIONES9A_WSDL_LOCATION;
    private static final WebServiceException PARCIAL1CONTRERASWEBOPERACIONES9A_EXCEPTION;
    private static final QName PARCIAL1CONTRERASWEBOPERACIONES9A_QNAME = new QName("http://contreras/", "parcial_1_contreras_web_operaciones_9a");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/parcial1_contreras_web_operaciones_9a/parcial_1_contreras_web_operaciones_9a?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PARCIAL1CONTRERASWEBOPERACIONES9A_WSDL_LOCATION = url;
        PARCIAL1CONTRERASWEBOPERACIONES9A_EXCEPTION = e;
    }

    public Parcial1ContrerasWebOperaciones9A_Service() {
        super(__getWsdlLocation(), PARCIAL1CONTRERASWEBOPERACIONES9A_QNAME);
    }

    public Parcial1ContrerasWebOperaciones9A_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), PARCIAL1CONTRERASWEBOPERACIONES9A_QNAME, features);
    }

    public Parcial1ContrerasWebOperaciones9A_Service(URL wsdlLocation) {
        super(wsdlLocation, PARCIAL1CONTRERASWEBOPERACIONES9A_QNAME);
    }

    public Parcial1ContrerasWebOperaciones9A_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PARCIAL1CONTRERASWEBOPERACIONES9A_QNAME, features);
    }

    public Parcial1ContrerasWebOperaciones9A_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Parcial1ContrerasWebOperaciones9A_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Parcial1ContrerasWebOperaciones9A
     */
    @WebEndpoint(name = "parcial_1_contreras_web_operaciones_9aPort")
    public Parcial1ContrerasWebOperaciones9A getParcial1ContrerasWebOperaciones9APort() {
        return super.getPort(new QName("http://contreras/", "parcial_1_contreras_web_operaciones_9aPort"), Parcial1ContrerasWebOperaciones9A.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Parcial1ContrerasWebOperaciones9A
     */
    @WebEndpoint(name = "parcial_1_contreras_web_operaciones_9aPort")
    public Parcial1ContrerasWebOperaciones9A getParcial1ContrerasWebOperaciones9APort(WebServiceFeature... features) {
        return super.getPort(new QName("http://contreras/", "parcial_1_contreras_web_operaciones_9aPort"), Parcial1ContrerasWebOperaciones9A.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PARCIAL1CONTRERASWEBOPERACIONES9A_EXCEPTION!= null) {
            throw PARCIAL1CONTRERASWEBOPERACIONES9A_EXCEPTION;
        }
        return PARCIAL1CONTRERASWEBOPERACIONES9A_WSDL_LOCATION;
    }

}
