
package contreras;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.1
 * Generated source version: 3.0
 * 
 */
@WebService(name = "parcial_1_contreras_web_operaciones_9a", targetNamespace = "http://contreras/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Parcial1ContrerasWebOperaciones9A {


    /**
     * 
     * @param resistencia
     * @param voltaje
     * @return
     *     returns double
     */
    @WebMethod(operationName = "calcular_IC")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "calcular_IC", targetNamespace = "http://contreras/", className = "contreras.CalcularIC")
    @ResponseWrapper(localName = "calcular_ICResponse", targetNamespace = "http://contreras/", className = "contreras.CalcularICResponse")
    @Action(input = "http://contreras/parcial_1_contreras_web_operaciones_9a/calcular_ICRequest", output = "http://contreras/parcial_1_contreras_web_operaciones_9a/calcular_ICResponse")
    public double calcularIC(
        @WebParam(name = "Voltaje", targetNamespace = "")
        double voltaje,
        @WebParam(name = "Resistencia", targetNamespace = "")
        double resistencia);

    /**
     * 
     * @param name
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "hello", targetNamespace = "http://contreras/", className = "contreras.Hello")
    @ResponseWrapper(localName = "helloResponse", targetNamespace = "http://contreras/", className = "contreras.HelloResponse")
    @Action(input = "http://contreras/parcial_1_contreras_web_operaciones_9a/helloRequest", output = "http://contreras/parcial_1_contreras_web_operaciones_9a/helloResponse")
    public String hello(
        @WebParam(name = "name", targetNamespace = "")
        String name);

}
